language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - echo "no dependencies to install"
script:
  - python setup.py build
  - python setup.py test
  - python setup.py test_kat
  - python setup.py speed
